<a href="https://colab.research.google.com/github/t7yutfru/biju/blob/main/numpy_pandas_casestudy_questionsc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 📚 **NumPy, Pandas, Matplotlib, and Seaborn Practice Questions**
---
This notebook contains four sets of practice questions covering NumPy, Pandas, Matplotlib, and Seaborn. Complete the tasks below and run the respective cells.

## 🧠 **Question 1: NumPy Array Manipulation**
1. Create a 1D NumPy array with integers from **1 to 24**.  
2. Reshape the array into a **4x6 matrix**.  
3. Extract the **third row** and **second column** from the reshaped array.  
4. Transpose the matrix and display the result.

In [2]:
# Solution for Question 1
import numpy as np
arr_1d = np.arange(1, 25)
print(arr_1d)
# Your code here

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [6]:
a=np.arange(1,25).reshape(4,6)
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [8]:
third_row=a[2,:]
second_row=a[:,1]
print(third_row)
print(second_row)

[ 3  9 15 21]
[ 7  8  9 10 11 12]


In [7]:
a=np.transpose(a)
print(a)

[[ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]
 [ 6 12 18 24]]


## 🧠 **Question 2: Array Element Extraction**
1. Create a **5x5 NumPy array** with random integers between **10 and 100**.  
2. Extract all the **even numbers** from the array.  
3. Replace all numbers **greater than 50** with **0**.  
4. Extract the diagonal elements of the array.

In [28]:
# Solution for Question 2
import numpy as np
arr3=np.random.randint(10,101,size=(5,5))
print(arr3)

# Your code here

[[30 47 59 15 41]
 [18 21 92 37 52]
 [45 95 38 95 29]
 [89 35 25 26 80]
 [72 50 72 70 97]]


In [16]:
arr3= np.arange(2,101,2)
print(arr3)


[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [23]:
arr3=np.arange(0,101)
arr3[arr3>50]=0
print(arr3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0]


In [29]:
arr3=np.diag(arr3)
print(arr3)

[30 21 38 26 97]


## 🧠 **Question 3: DataFrame Creation and Operations (Pandas)**
1. Create a Pandas DataFrame containing the following data:

| Student_ID | Name   | Subject | Marks |
|------------|--------|---------|-------|
| 1          | Alice  | Math    | 88    |
| 2          | Bob    | Science | 75    |
| 3          | Carol  | History | 92    |
| 4          | David  | Math    | 85    |
| 5          | Eva    | Science | 90    |

2. Find the **average marks** for each subject.  
3. Add a new column named **Grade** based on the marks:
- Marks ≥ 90 → A
- Marks ≥ 80 → B
- Marks ≥ 70 → C
- Else → D

In [4]:
# Solution for Question 3
import pandas as pd
arr_2d = np.random.randint(10, 101, size=(5, 5))
print(arr_2d)
# Your code here

[[79 14 21 43 16]
 [88 42 62 89 90]
 [68 54 61 51 56]
 [67 75 33 51 10]
 [97 33 10 33 40]]


In [30]:
np.average(arr_2d)

51.32

In [45]:
data={'student id':[1,2,3,4,5],'name':['alice','bob','carol','david','eva'],'subject':['math','science','history','math','science'],'marks':[88,75,92,85,90],'grade':['a','a','c','b','d']}

In [52]:
def assign_grade(marks):
    if marks >= 90:
        return "A"
    elif marks >= 80:
        return "B"
    elif marks >=70:
        return "C"
    else:
        return "D"
df['Grade']=df['Marks'].apply(assign_grade)
print(df)

NameError: name 'df' is not defined

## 🧠 **Question 4: Dataset Analysis (Pandas, Matplotlib, Seaborn)**
Use the dataset `diabetes.csv` and perform the following tasks:

1. Display the **BMI** and **Blood Pressure** for samples with **index ranging from 20 to 40**.  
2. Find how many patients have **BMI > 30**.  
3. Find the **mean and standard deviation** of the **Glucose** levels.  
4. Plot a **boxplot** for the column **Insulin**.  
5. Create a **heatmap** showing the correlation between the numerical columns in the dataset.

In [46]:
# Solution for Question 4
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

[
    "Pregnancies",
    "Glucose",
    "BloodPressure",
    "SkinThickness",
    "Insulin",
    "BMI",
    "DiabetesPedigreeFunction",
    "Age",
    "Outcome",


]
# Your code here

['Pregnancies',
 'Glucose',
 'BloodPressure',
 'SkinThickness',
 'Insulin',
 'BMI',
 'DiabetesPedigreeFunction',
 'Age',
 'Outcome']